### ISSUE TITLE
KeyError in calculate_cpu_percentage function

### ISSUE THREAD

**Issue by SeyedEhsanHosseini** [Shayan-Ghani/Container-Exporter#2]
**The problem is with '_percpu_usage_' key in below line of function** 

cpu_percent = (cpu_delta / system_delta) * len(stats['cpu_stats']['cpu_usage']['percpu_usage']) * 100.0

**Comment by SeyedEhsanHosseini** [comment]
Of course ! As you can see from the stats output of an nginx container in this example, there is no '**percpu_usage**' key in the output data.
```
{
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 25913000,
      "usage_in_kernelmode": 12956000,
      "usage_in_usermode": 12956000
    },
    "system_cpu_usage": 385500140000000,
    "online_cpus": 8,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 25913000,
      "usage_in_kernelmode": 12956000,
      "usage_in_usermode": 12956000
    },
    "system_cpu_usage": 385492170000000,
    "online_cpus": 8,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  }
}
```

**Comment by Shayan-Ghani** [comment]
Got it, It seems to me that percpu and totalcpu has become isolated in your shared output, which makes sense. You can get it fixed by replacing it with: `cpu_percent = (cpu_delta / system_delta) * len(stats['cpu_stats']['cpu_usage']['total_usage']) * 100.0 
`
Or use reference for percpu_stats accordingly. 

Odds are, the issue either relates to specific cases and versions or docker version in general that being said, I am going to probe some testcases throughly to find out the reason that's causing this drift.

Thanks.

**Comment by Shayan-Ghani** [comment]
You have a point right there, the calculation of CPU is under revision and will soon be updated in addition to the unit in bytes.
